import { JourneyEvent } from '../../../core/types/domain';

export interface FieldDef {
  name: string;
  value: string | number | boolean;
  isClue?: boolean; // Fields that reveal the root cause
  gapCategory: 'trace' | 'customer' | 'security' | 'timing' | 'infra';
}

export const JOURNEY_FIELDS: Record<JourneyEvent, FieldDef[]> = {
  [JourneyEvent.CONNECT]: [
    { name: 'client_ip', value: '203.45.67.89', gapCategory: 'security' },
    { name: 'source_port', value: 54321, gapCategory: 'infra' },
    { name: 'destination_ip', value: '10.0.1.42', gapCategory: 'infra' },
    { name: 'connection_id', value: 'conn-8f4a2b1c', gapCategory: 'trace' },
    { name: 'protocol', value: 'HTTP/1.1', gapCategory: 'infra' },
    { name: 'keep_alive', value: true, gapCategory: 'infra' },
    { name: 'tcp_flags', value: 'SYN,ACK', gapCategory: 'infra' },
    { name: 'mtu_size', value: 1500, gapCategory: 'infra' },
    { name: 'socket_buffer', value: 65536, gapCategory: 'infra' },
    { name: 'proxy_protocol', value: 'v2', gapCategory: 'infra' },
  ],
  [JourneyEvent.TLS_HANDSHAKE]: [
    {
      name: 'tls_version',
      value: 'TLS 1.0',
      isClue: true,
      gapCategory: 'security',
    },
    { name: 'cipher', value: 'RC4-SHA', isClue: true, gapCategory: 'security' },
    { name: 'sni_hostname', value: 'shop.example.com', gapCategory: 'infra' },
    { name: 'client_hello_size', value: 512, gapCategory: 'timing' },
    { name: 'handshake_duration_ms', value: 245, gapCategory: 'timing' },
    { name: 'cert_chain_length', value: 3, gapCategory: 'security' },
    { name: 'ocsp_status', value: 'good', gapCategory: 'security' },
    { name: 'alpn_protocol', value: 'h2', gapCategory: 'infra' },
    { name: 'session_resumed', value: false, gapCategory: 'timing' },
    { name: 'early_data', value: false, gapCategory: 'timing' },
  ],
  [JourneyEvent.WAF_CHECK]: [
    { name: 'rules_checked', value: 147, gapCategory: 'security' },
    { name: 'waf_score', value: 35, gapCategory: 'security' },
    { name: 'waf_action', value: 'allow', gapCategory: 'security' },
    { name: 'risk_level', value: 'medium', gapCategory: 'security' },
    {
      name: 'matched_rules',
      value: 'sqli-001,xss-003',
      gapCategory: 'security',
    },
    { name: 'payload_size', value: 2048, gapCategory: 'infra' },
    { name: 'request_method', value: 'POST', gapCategory: 'trace' },
    { name: 'uri_path', value: '/api/checkout', gapCategory: 'trace' },
    { name: 'query_params', value: 'ref=home', gapCategory: 'trace' },
    { name: 'content_type', value: 'application/json', gapCategory: 'infra' },
  ],
  [JourneyEvent.GEO_CHECK]: [
    { name: 'country', value: 'IR', isClue: true, gapCategory: 'security' },
    { name: 'region', value: 'Tehran', gapCategory: 'security' },
    { name: 'city', value: 'Tehran', gapCategory: 'security' },
    { name: 'asn', value: 44889, gapCategory: 'security' },
    { name: 'asn_org', value: 'TIC', gapCategory: 'security' },
    { name: 'is_vpn', value: false, gapCategory: 'security' },
    { name: 'is_proxy', value: false, gapCategory: 'security' },
    { name: 'is_tor', value: false, gapCategory: 'security' },
    { name: 'is_datacenter', value: false, gapCategory: 'security' },
    {
      name: 'is_sanctioned',
      value: true,
      isClue: true,
      gapCategory: 'security',
    },
  ],
  [JourneyEvent.BOT_CHECK_START]: [
    { name: 'bot_score', value: 0.89, isClue: true, gapCategory: 'security' },
    { name: 'headless', value: false, gapCategory: 'security' },
    { name: 'webdriver', value: false, gapCategory: 'security' },
    { name: 'plugins_count', value: 3, gapCategory: 'security' },
    { name: 'screen_res', value: '1920x1080', gapCategory: 'security' },
    { name: 'timezone', value: 'Asia/Tehran', gapCategory: 'customer' },
    { name: 'language', value: 'fa-IR', gapCategory: 'customer' },
    { name: 'canvas_hash', value: 'a1b2c3d4', gapCategory: 'security' },
    { name: 'webgl_hash', value: 'e5f6g7h8', gapCategory: 'security' },
    { name: 'audio_hash', value: 'i9j0k1l2', gapCategory: 'security' },
  ],
  [JourneyEvent.JS_CHALLENGE]: [
    { name: 'challenge_id', value: 'ch-9f8e7d6c', gapCategory: 'trace' },
    { name: 'challenge_type', value: 'proof-of-work', gapCategory: 'security' },
    {
      name: 'challenge_start',
      value: '2026-01-26T00:01:55.000Z',
      gapCategory: 'timing',
    },
    {
      name: 'challenge_end',
      value: '2026-01-26T00:01:57.234Z',
      gapCategory: 'timing',
    },
    { name: 'solve_duration_ms', value: 2234, gapCategory: 'timing' },
    { name: 'js_environment', value: 'browser', gapCategory: 'security' },
    { name: 'worker_support', value: true, gapCategory: 'security' },
    { name: 'wasm_support', value: true, gapCategory: 'security' },
    { name: 'memory_available', value: 8192, gapCategory: 'infra' },
    { name: 'cpu_cores', value: 8, gapCategory: 'infra' },
  ],
  [JourneyEvent.CAPTCHA_PRESENTED]: [
    { name: 'captcha_type', value: 'image-select', gapCategory: 'security' },
    { name: 'captcha_provider', value: 'internal', gapCategory: 'infra' },
    { name: 'difficulty_level', value: 'medium', gapCategory: 'security' },
    { name: 'image_count', value: 9, gapCategory: 'security' },
    { name: 'audio_available', value: true, gapCategory: 'customer' },
    { name: 'load_time_ms', value: 156, gapCategory: 'timing' },
    { name: 'render_time_ms', value: 42, gapCategory: 'timing' },
    { name: 'session_token', value: 'cap-abc123', gapCategory: 'trace' },
    { name: 'fallback_used', value: false, gapCategory: 'infra' },
    { name: 'accessibility_mode', value: false, gapCategory: 'customer' },
  ],
  [JourneyEvent.CAPTCHA_SOLVED]: [
    { name: 'solve_time_ms', value: 8456, gapCategory: 'timing' },
    { name: 'attempts', value: 1, gapCategory: 'customer' },
    { name: 'correct_answers', value: 3, gapCategory: 'security' },
    { name: 'timeout_occurred', value: false, gapCategory: 'timing' },
    { name: 'client_drift_ms', value: 12, gapCategory: 'timing' },
    { name: 'interaction_events', value: 47, gapCategory: 'customer' },
    { name: 'mouse_movements', value: 234, gapCategory: 'security' },
    { name: 'keypress_count', value: 0, gapCategory: 'security' },
    { name: 'tab_switches', value: 0, gapCategory: 'security' },
    { name: 'paste_detected', value: false, gapCategory: 'security' },
  ],
  [JourneyEvent.INTEGRITY_PASSED]: [
    { name: 'integrity_score', value: 72, gapCategory: 'security' },
    { name: 'device_fingerprint', value: 'fp-xyz789', gapCategory: 'security' },
    { name: 'device_age_days', value: 0, gapCategory: 'customer' },
    { name: 'known_device', value: false, gapCategory: 'customer' },
    {
      name: 'risk_signals',
      value: 'new_device,foreign_ip',
      gapCategory: 'security',
    },
    { name: 'behavioral_score', value: 65, gapCategory: 'security' },
    { name: 'velocity_check', value: 'pass', gapCategory: 'security' },
    { name: 'linked_accounts', value: 0, gapCategory: 'customer' },
    { name: 'trust_level', value: 'low', gapCategory: 'security' },
    { name: 'fraud_flags', value: 'none', gapCategory: 'security' },
  ],
  [JourneyEvent.QUEUE_ENTER]: [
    { name: 'queue_id', value: 'q-standard-01', gapCategory: 'infra' },
    { name: 'queue_name', value: 'Standard Queue', gapCategory: 'infra' },
    { name: 'initial_position', value: 4521, gapCategory: 'customer' },
    { name: 'est_wait_seconds', value: 180, gapCategory: 'timing' },
    { name: 'queue_length', value: 12000, gapCategory: 'infra' },
    { name: 'priority_boost', value: 0, gapCategory: 'customer' },
    { name: 'segment_multiplier', value: 1.0, gapCategory: 'customer' },
    { name: 'max_wait', value: 600, gapCategory: 'timing' },
    { name: 'served_rate', value: 25, gapCategory: 'timing' },
    { name: 'bypass_eligible', value: false, gapCategory: 'customer' },
  ],
  [JourneyEvent.QUEUE_POLL_1]: [
    { name: 'position', value: 3890, gapCategory: 'customer' },
    { name: 'position_delta', value: -631, gapCategory: 'timing' },
    { name: 'poll_latency_ms', value: 45, gapCategory: 'timing' },
    {
      name: 'server_time',
      value: '2026-01-26T00:02:05.000Z',
      gapCategory: 'timing',
    },
    {
      name: 'client_time',
      value: '2026-01-26T00:02:05.012Z',
      gapCategory: 'timing',
    },
    { name: 'drift_ms', value: 12, gapCategory: 'timing' },
    { name: 'retry_count', value: 0, gapCategory: 'infra' },
    { name: 'connection_quality', value: 'good', gapCategory: 'infra' },
    { name: 'poll_interval', value: 5000, gapCategory: 'timing' },
    {
      name: 'next_poll_at',
      value: '2026-01-26T00:02:10.000Z',
      gapCategory: 'timing',
    },
  ],
  [JourneyEvent.QUEUE_POLL_2]: [
    { name: 'position', value: 2456, gapCategory: 'customer' },
    { name: 'remaining_wait', value: 98, gapCategory: 'timing' },
    { name: 'users_ahead', value: 2455, gapCategory: 'infra' },
    { name: 'estimated_rate', value: 25, gapCategory: 'timing' },
    { name: 'queue_health', value: 'healthy', gapCategory: 'infra' },
    { name: 'congestion_level', value: 'low', gapCategory: 'infra' },
    {
      name: 'predicted_admit_time',
      value: '2026-01-26T00:03:45.000Z',
      gapCategory: 'timing',
    },
    { name: 'slot_availability', value: 85, gapCategory: 'infra' },
    { name: 'capacity_percentage', value: 72, gapCategory: 'infra' },
    { name: 'dynamic_priority', value: 1.2, gapCategory: 'customer' },
  ],
  [JourneyEvent.QUEUE_NEXT]: [
    { name: 'promoted', value: true, gapCategory: 'customer' },
    {
      name: 'promotion_reason',
      value: 'position_reached',
      gapCategory: 'customer',
    },
    { name: 'final_position', value: 1, gapCategory: 'customer' },
    { name: 'total_wait_time', value: 145000, gapCategory: 'timing' },
    { name: 'fairness_score', value: 0.98, gapCategory: 'customer' },
    { name: 'segment_rank', value: 'standard', gapCategory: 'customer' },
    { name: 'vip_override', value: false, gapCategory: 'customer' },
    { name: 'emergency_bypass', value: false, gapCategory: 'infra' },
    { name: 'slot_id', value: 'slot-7f3e2d1c', gapCategory: 'trace' },
    { name: 'admit_window', value: 30000, gapCategory: 'timing' },
  ],
  [JourneyEvent.TOKEN_GRANT]: [
    { name: 'token_type', value: 'access', gapCategory: 'security' },
    { name: 'token_ttl', value: 3600, gapCategory: 'timing' },
    {
      name: 'signing_node',
      value: 'token-svc-03',
      isClue: true,
      gapCategory: 'infra',
    },
    {
      name: 'signing_algorithm',
      value: 'ES256',
      isClue: true,
      gapCategory: 'security',
    },
    { name: 'key_id', value: 'key-2026-01', gapCategory: 'security' },
    { name: 'token_size', value: 0, gapCategory: 'infra' },
    { name: 'claims_count', value: 0, gapCategory: 'security' },
    { name: 'audience', value: 'shop.example.com', gapCategory: 'infra' },
    { name: 'issuer', value: 'auth.example.com', gapCategory: 'infra' },
    { name: 'token_hash', value: 'N/A', gapCategory: 'trace' },
  ],
  [JourneyEvent.ADMITTED]: [
    { name: 'session_token', value: 'N/A', gapCategory: 'trace' },
    { name: 'final_action', value: 'blocked', gapCategory: 'security' },
    { name: 'origin_target', value: '/checkout', gapCategory: 'trace' },
    { name: 'origin_ip', value: '10.0.2.15', gapCategory: 'infra' },
    { name: 'origin_latency_ms', value: 0, gapCategory: 'timing' },
    { name: 'load_balancer', value: 'lb-west-02', gapCategory: 'infra' },
    { name: 'sticky_session', value: false, gapCategory: 'infra' },
    { name: 'cache_status', value: 'miss', gapCategory: 'infra' },
    { name: 'response_code', value: 500, gapCategory: 'infra' },
    { name: 'bytes_transferred', value: 0, gapCategory: 'timing' },
  ],
};

// GAP_NAMES and STEP_COLORS moved to core/constants
